---
abstract: 'routines to work with a perl nested data structure'
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Nested
provides:
  Data::Nested:
    file: lib/Data/Nested.pm
    version: 3.12
  Data::Nested::Multiele:
    file: lib/Data/Nested/Multiele.pm
    version: 3.12
  Data::Nested::Multifile:
    file: lib/Data/Nested/Multifile.pm
    version: 3.12
requires:
  Algorithm::Permute: 0
  IO::File: 0
  Storable: 0
  YAML::Syck: 0
  perl: 5.001
resources:
  license: http://dev.perl.org/licenses/
version: 3.12
