perl -I../lib check_structure.t 1
perl -I../lib check_value.t 1
perl -I../lib delim.t 1
perl -I../lib empty_1.t 1
perl -I../lib empty_2.t 1
perl -I../lib erase_1.t 1
perl -I../lib erase_2.t 1
perl -I../lib erase_3.t 1
perl -I../lib get_merge.t 1
perl -I../lib get_structure.t 1
perl -I../lib identical.t 1
perl -I../lib keys.t 1
perl -I../lib merge_1.t 1
perl -I../lib merge_2.t 1
perl -I../lib merge_path_1.t 1
perl -I../lib merge_path_2.t 1
perl -I../lib merge_path_3.t 1
perl -I../lib nds_1.t 1
perl -I../lib nds_2.t 1
perl -I../lib nds_3.t 1
perl -I../lib path_1.t 1
perl -I../lib path_2.t 1
perl -I../lib paths.t 1
perl -I../lib ruleset.t 1
perl -I../lib ruleset_valid.t 1
perl -I../lib set_merge.t 1
perl -I../lib set_structure.t 1
perl -I../lib test_conditions.hash.t 1
perl -I../lib test_conditions.list.t 1
perl -I../lib test_conditions.scalar.t 1
perl -I../lib value.t 1
perl -I../lib values.t 1
perl -I../lib which_1.t 1
perl -I../lib which_2.t 1
